# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: terragis_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'terragis_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16terragis_service.proto\x12\x0bterragis.v1\" \n\x0bPingRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"=\n\x0cPingResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x1c\n\x14server_time_epoch_ms\x18\x02 \x01(\x03\"\xb3\x01\n\x12SegmentTileRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x14\n\x0craster_width\x18\x02 \x01(\x05\x12\x15\n\rraster_height\x18\x03 \x01(\x05\x12\x0e\n\x06tile_x\x18\x04 \x01(\x05\x12\x0e\n\x06tile_y\x18\x05 \x01(\x05\x12\x12\n\ntile_width\x18\x06 \x01(\x05\x12\x13\n\x0btile_height\x18\x07 \x01(\x05\x12\x13\n\x0braster_path\x18\x08 \x01(\t\"|\n\x13SegmentTileResponse\x12\x12\n\nmask_width\x18\x01 \x01(\x05\x12\x13\n\x0bmask_height\x18\x02 \x01(\x05\x12\x13\n\x0bpacked_mask\x18\x03 \x01(\x0c\x12\x13\n\x0b\x63lass_label\x18\x04 \x01(\t\x12\x12\n\nconfidence\x18\x05 \x01(\x01\x32\xa0\x01\n\x0fTerraApiService\x12;\n\x04Ping\x12\x18.terragis.v1.PingRequest\x1a\x19.terragis.v1.PingResponse\x12P\n\x0bSegmentTile\x12\x1f.terragis.v1.SegmentTileRequest\x1a .terragis.v1.SegmentTileResponseB&\n\x13\x63om.terra.gis.protoB\rTerraGisProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'terragis_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.terra.gis.protoB\rTerraGisProtoP\001'
  _globals['_PINGREQUEST']._serialized_start=39
  _globals['_PINGREQUEST']._serialized_end=71
  _globals['_PINGRESPONSE']._serialized_start=73
  _globals['_PINGRESPONSE']._serialized_end=134
  _globals['_SEGMENTTILEREQUEST']._serialized_start=137
  _globals['_SEGMENTTILEREQUEST']._serialized_end=316
  _globals['_SEGMENTTILERESPONSE']._serialized_start=318
  _globals['_SEGMENTTILERESPONSE']._serialized_end=442
  _globals['_TERRAAPISERVICE']._serialized_start=445
  _globals['_TERRAAPISERVICE']._serialized_end=605
# @@protoc_insertion_point(module_scope)
